/*******************************************************************************
* File Name: project.h
* 
* PSoC Creator  4.4
*
* Description:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "SDA_aliases.h"
#include "SDA.h"
#include "SCL_aliases.h"
#include "SCL.h"
#include "I2C_Master.h"
#include "I2C_Master_PVT.h"
#include "SW_aliases.h"
#include "SW.h"
#include "BUILT_IN_LED_aliases.h"
#include "BUILT_IN_LED.h"
#include "UART.h"
#include "ISR_DEB.h"
#include "Clock_DEB.h"
#include "ADC_DelSig_1.h"
#include "TEMP_aliases.h"
#include "TEMP.h"
#include "EXT_LED_aliases.h"
#include "EXT_LED.h"
#include "ISR_ACC.h"
#include "INT_ACC_aliases.h"
#include "INT_ACC.h"
#include "ISR_RX.h"
#include "ISR_TX.h"
#include "UART_IntClock.h"
#include "ADC_DelSig_1_AMux.h"
#include "ADC_DelSig_1_Ext_CP_Clk.h"
#include "ADC_DelSig_1_IRQ.h"
#include "ADC_DelSig_1_theACLK.h"
#include "core_cm3_psoc5.h"
#include "CyDmac.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cypins.h"
#include "cyPm.h"
#include "CySpc.h"
#include "cytypes.h"
#include "cy_em_eeprom.h"

/*[]*/

